Join Group Screen
TheFenix2000/unievent-planner-frontend pull request #3
Opened 2024-07-18 10:12 UTC by paulinapp1

screen which allows you to join or create a group, with input code

2024-09-26 07:46 UTC, Aghon5304 reviewed
po rebase sprawdz swoje pliki czy nie trzeba poprawić czegoś prettierem

2024-11-25 21:22 UTC, Aghon5304 commented on src/App.tsx
> +      <JoinGroup />
usuń joinGroup z app

2024-11-25 21:25 UTC, Aghon5304 requested changes

2024-11-25 21:25 UTC, Aghon5304 commented on src/screens/JoinGroupScreen/JoinGroupScreenStyles.ts
na discordzie na #kalendarz_apka jest wiadomość z wielkościami jakie używamy takimi jak między innymi wielkość frontów. musisz przejrzeć to i zmienić u siebie

2024-11-25 21:26 UTC, Aghon5304 commented on src/screens/JoinGroupScreen/JoinGroupScreenStyles.ts
> +  color: white;
+ nadal są jakieś konflikty

2024-12-12 11:24 UTC, Aghon5304 requested changes

2024-12-12 11:24 UTC, Aghon5304 commented on src/screens/JoinGroupScreen/JoinGroupScreenStyles.ts
masz w zbyt dużej ilości miejsc dany padding. Co najmniej dwa elementy mają padding 2 rem co sprawia że się na siebie nakładają. strona nie jest także wycentrowana
![image](https://github.com/user-attachments/assets/f33ccb32-abc7-4d16-a196-dd4ae513f414)

2024-12-12 11:24 UTC, Aghon5304 commented on package.json
usunełaś mui-material przez co nie da się uruchomić twojej strony.
musisz zrobić ```npm install @mui/material @emotion/react @emotion/styled```

2025-02-02 12:14 UTC, Aghon5304 requested changes
wygląda dobrze. Trzeba będzie tylko spłaszczyć ilość commitów do jednego i można mergować. Aby spłaszczyć commity możesz np. użyć `git reset --soft idierwszyCommit
git commit --amend
git push --force`

2025-02-09 16:05 UTC, Aghon5304 approved these changes
można mergować :)

2025-02-09 16:09 UTC, Aghon5304 requested changes
trzeba będzie jeszcze zrebaseować a potem jeszcze raz zpłaszczyć

2025-02-09 16:31 UTC, paulinapp1 commented
> trzeba będzie jeszcze zrebaseować a potem jeszcze raz spłaszczyć

zrebasowane

2025-02-09 21:36 UTC, Aghon5304 approved these changes

2025-02-09 21:36 UTC, merged